Added actions for when user clicks on blue "Ratings" button in ProductContent
femi-icarcover/coverland pull request #123
Opened 2024-02-07 22:21 UTC by george-icarcover

2024-02-08 23:48 UTC, george-icarcover commented
### Populated ReviewHeaderGallery with real review data:

**Mobile**
![image](https://github.com/femi-icarcover/coverland/assets/156227633/94e480e3-ca34-4cb8-a041-027e2fa9c7a8)
**Desktop**
![image](https://github.com/femi-icarcover/coverland/assets/156227633/09fd841c-24b3-4677-8d9f-34caa59ec309)

### Populated CustomerReviewTabs  with real review data
**Mobile**
![image](https://github.com/femi-icarcover/coverland/assets/156227633/7ca041b2-9476-43e1-98a7-e2270cfd6f0b)
![image](https://github.com/femi-icarcover/coverland/assets/156227633/ce078ad3-e481-440f-a493-459a2a84d865)
_Left out the mobile carousel because it should be in another branch and Ashley said she will have a redesign_

**Desktop**
![image](https://github.com/femi-icarcover/coverland/assets/156227633/fd1e9f9a-63d8-4ef7-9c81-8045647dd455)
![image](https://github.com/femi-icarcover/coverland/assets/156227633/db03d95c-cb0e-4141-a928-75a2ff34659a)

2024-02-09 00:58 UTC, devwilliamy requested changes
Left comments on code. **Please reply** that you've read & confirmed what I've commented on.

Please also update the table to not look at Mock-Data-Reviews but reviews-2

2024-02-09 00:58 UTC, devwilliamy commented on src/components/PDP/components/ReviewHeaderGallery.tsx
> +          if (index <= 4) {
You should add a .slice before the map to make the array smaller if you're going to check by index.

Even if you're checking for the index, the map will still attempt to map thru the array.

2024-02-09 00:58 UTC, devwilliamy commented on src/lib/db/review/index.ts
> +    for (const ob of data) {
Correct me if I'm wrong, but it looks like this will only return 2 things.

Can you verify there aren't any review images that have more than 2 commas in them? You can run a SQL script to check. Let me know if you need a script to check it.

Also, is it enough to just return the image string here? Please let me know what's supposed to happen when you click on an image.

2024-02-09 01:19 UTC, devwilliamy commented
- Review Images too close to the container on top of it (the contaienr with the stars and the green circle)

![image](https://github.com/femi-icarcover/coverland/assets/156253900/d6d4463f-0764-4250-92ff-2a944fbaadd5)

- Customer Images takes some time to load. Hopefully this is fixed by putting these images in the store and be ready before hand. I also can't click on Customer Reviews while it's loading, is this intended?
- Please confirm, if I click on one of these is it supposed to take me somewhere? I have a strong feeling it should and you might need more than just the image.
![image](https://github.com/femi-icarcover/coverland/assets/156253900/c842d25d-09c7-47eb-92e6-d911c853d7a9)

- Is this the right photo? I'm guessing this review didn't have a photo...? Should it have a photo or no photo if it doesn't have one? Please confirm.

![image](https://github.com/femi-icarcover/coverland/assets/156253900/8bf7a8b2-1385-4cd2-85c4-bcbd4aa04a50)

- Please have this match the figma (desktop). Check the title, review content, font size font weight etc.  Also ensure it doesn't mess up mobile.

Yours
![image](https://github.com/femi-icarcover/coverland/assets/156253900/a428e4da-fb0a-4412-9407-fb0fe872efc5)

Figma
![image](https://github.com/femi-icarcover/coverland/assets/156253900/d07d034f-4356-4ab4-a7ee-e94daafcf23f)

- I can't show this one, but can you confirm what should happen after you finish clicking on the fourth review? It currently closes. I'm guessing they'll want to load more. **Please confirm**

- Can you confirm they want the blue reviews to go to customer images? That doesn't sound right. I feel like it should go to Customer Reviews. Or last I heard about it, to the bottom reviews. 

- Can you confirm if they wanted THIS to go to customer images?

![image](https://github.com/femi-icarcover/coverland/assets/156253900/17ea942a-4bef-4a7a-9ba7-9b7a635c975b)

- Can you also make it so the same images don't show up? Actually, please confirm what Ashley/Calvin think should happen. femi did mention this:

> For PDP pages that show more than just one car model (e.g. productType, or make pages), we'll need to make sure we don't duplicate any images. Currently many products repeat the same images, so we'll have to account for this. For example: on car-covers/bmw, because a 3-Series and 5-Series vehicle might share the same review images, we'd only want to show the images on one of the products/reviews and leave the other blank

If you look on /car-covers, customer images have a lot of repeats. **Please reach out** if you need help getting started / checking if you're going in the right direction

- I tried SUV cover reviews, can you confirm if there's actually no images or if this is an issue on your side?

![image](https://github.com/femi-icarcover/coverland/assets/156253900/43f07665-3fcc-482b-abd0-37bfa4e0a9eb)

2024-02-09 02:06 UTC, devwilliamy commented on src/components/PDP/components/CustomerReviewTabs.tsx
> +    getAllImages();
JK on behavior for submodel, the review will tie to model and then for year it's parent generation

From calvin (he gets the years wrong, but the concept is there): 

> So, if someone leaves a review for 2005-2019 BMW 3-Series Sedan, it will only tie to the 2005-2019 BMW 3-Series.

> 2006-2018 BMW 3-series convertible review will tie to 2005-2019 BMW 3-Series. When the user goes to the 2006-2018 BMW 3-series convertible, the user will see all the reviews related to 2005-2019 BMW 3-Series and also can see the reviews for sedan, coupe, convertible, wagon, whatever submodel it's tied to the parent year generation

2024-02-09 22:48 UTC, george-icarcover commented on src/components/PDP/components/CustomerReviewTabs.tsx
> +                      : ExampleImage
Ashley said if there is no image just display the review at full width

2024-02-13 18:30 UTC, devwilliamy reviewed
I left some comments that aren't show stoppers but I would really like you to correct them.

If we need to get this over the finish line, can move forward, but I would like you to make the changes after

However, I'm doing this check before some of your changes so I might have some more comments after.

2024-02-13 18:30 UTC, devwilliamy commented on src/app/(main)/[productType]/page.tsx
> +  let reviewImages: any[] = [];
This should not be `any[]`, think it should be `string[]`

2024-02-13 18:30 UTC, devwilliamy commented on src/app/(main)/[productType]/page.tsx
> +    productType === 'car-covers' ? defaultCarModelData : isSuvData;
While I understand you're trying to break this up into smaller pieces, I think the readability gets lost.
It's also not a good code convention to use `is____` as not a boolean. `isSuvData` I would think is a boolean but here we're setting an array of objects to it. And then on line 32, if I read this from the get go, it looks like if product data is car covers, we'll take the `defaultCarModelData`. But if it's not, then we'll take a true or false value, which doesn't make sense for `modelData`. 

Something that would make sense for `isSuvData` is this:
```javascript
const isCarData = productType === 'car-covers';
const isSuvData = productType === 'suv-covers';

const modelData = isCarData ? defaultCarModelData : isSuvData ? defaultSuvModelData : defaultTruckModelData
```

Let me know if you have another reasoning for this change, otherwise I would suggest setting it back to what it was.

2024-02-13 18:30 UTC, devwilliamy commented on src/app/(main)/[productType]/page.tsx
> +    params?.productType === 'car-covers' ? 'Car Covers' : isSuvType;
Same as above comment, would suggest changing it back.

2024-02-13 18:30 UTC, devwilliamy commented on src/components/PDP/components/CustomerReviewTabs.tsx
> +  const typeString = type === 'car-covers' ? 'Car Covers' : isSuvTypeString;
Same as above comment

2024-02-13 18:30 UTC, devwilliamy commented on src/components/PDP/components/ReviewCard.tsx
> +         <></>
I don't know if this is a placeholder for something you're working on but if this is the final, you can put null here instead of an empty fragment.

2024-02-13 18:30 UTC, devwilliamy commented on src/components/PDP/components/ReviewCardImages.tsx
> +  //   return images;
If you don't need this, delete it

2024-02-13 18:30 UTC, devwilliamy commented on src/components/PDP/components/ReviewHeaderGallery.tsx
> +            {reviewImages?.length > 0 ? (
Should this be length > 0 ? Or length > 3?

2024-02-13 18:30 UTC, devwilliamy commented on src/components/PDP/components/ReviewHeaderGallery.tsx
> +            {reviewImages?.length > 0 ? (
Should this be length > 0 ? or length > 5?

2024-02-13 18:30 UTC, devwilliamy commented on src/components/PDP/components/ReviewSection.tsx
> +  const typeString = type === 'car-covers' ? 'Car Covers' : isSuvTypeString;
Same as above comment

2024-02-13 18:30 UTC, devwilliamy commented on src/lib/db/review/index.ts
> +  console.log('running fetch');
can you clean up random console logs

2024-02-13 22:19 UTC, devwilliamy requested changes
Please check my previous comments as well

Also I'm blocking it because you need to have the images show up on /make and /make/model and /make/model/year pages as well

2024-02-13 22:19 UTC, devwilliamy commented on src/app/(main)/[productType]/components/SelectedProductImages.tsx
>              `}
Can you clean this up please

2024-02-13 22:19 UTC, devwilliamy commented on src/lib/db/review/index.ts
> +    return Array.from(imageMap);
Should this be returning an array or can it just return the map?

2024-02-13 22:28 UTC, devwilliamy commented
- Images aren't showing up. I'm guessing it's because of the map. Check my comment above on whether it should be an array or you return the map and you handle the map differently.

![image](https://github.com/femi-icarcover/coverland/assets/156253900/4a811d72-a842-4027-b601-00411eca438d)

- I don't believe you're using checking if an image has been shown yet

1st review:
![image](https://github.com/femi-icarcover/coverland/assets/156253900/27dc9ab7-69bb-4494-9280-3f1eb5763947)

2nd review:
![image](https://github.com/femi-icarcover/coverland/assets/156253900/b7129d24-19f3-483d-819b-8609c6389f51)

- I'm seeing a lot of these Image missing src property. Can you address these? (could be related to the pictures not showing up)

![image](https://github.com/femi-icarcover/coverland/assets/156253900/a68ba531-7fdb-4e7b-99db-b6202ec99010)

- We should comment helpful out because we don't have it implemented yet

![image](https://github.com/femi-icarcover/coverland/assets/156253900/cae0120f-06d2-4df4-87ca-a09c759dca8a)

2024-02-13 23:08 UTC, george-icarcover commented on src/components/PDP/components/ReviewHeaderGallery.tsx
> +            {reviewImages?.length > 0 ? (
No, just making sure that there are items in reviewImages

2024-02-14 19:41 UTC, merged