[CK REQUEST] - Randomize red "Only # left" on PDP pages
femi-icarcover/coverland pull request #47
Opened 2024-01-25 21:37 UTC by george-icarcover

- Added calculations for Only # left to ProductContent and CarSelector

2024-01-25 21:52 UTC, devwilliamy requested changes
I'm not sure if it's working as intended. The number isn't changing when I choose different colors.


![image](https://github.com/femi-icarcover/coverland/assets/156253900/bf549409-4547-4ee2-a1c1-2e5cada4e5e3)
![image](https://github.com/femi-icarcover/coverland/assets/156253900/eec31816-f361-47a5-af03-76fea436ee4f)

![image](https://github.com/femi-icarcover/coverland/assets/156253900/5be8bb03-77db-494b-94c9-335f564dc57d)
![image](https://github.com/femi-icarcover/coverland/assets/156253900/cc902d62-e006-453d-a924-d95559f92bf1)

2024-01-25 21:52 UTC, devwilliamy commented on src/app/(main)/car-covers/components/ProductContent.tsx
> +  let productAmount = 0;
I highly recommend extracting this as a function and putting it in a utils file. I believe we have a lib/utils file.
Another path would be turning the only # left into a component and having the logic as a function in that component and then you can re-use that component across the two.

2024-01-25 21:52 UTC, devwilliamy commented on src/app/(main)/car-covers/components/ProductContent.tsx
> +  let p = selectedProduct;
`p` is never updated you don't need this variable. You can just use `selectedProduct` instead.

I also highly discourage the use of single letter variables outside of a for loop or something similar

2024-01-25 21:52 UTC, devwilliamy commented on src/app/(main)/car-covers/components/ProductContent.tsx
> +    let string = productAmount.toString();
I also highly discourage using types as variable names themselves. It's vague upon first reading,  `productAmountStr` would be better (although I discourage that convention as well)

2024-01-25 21:52 UTC, devwilliamy commented on src/app/(main)/car-covers/components/ProductContent.tsx
> +    for (let i = 5; i < string.length; i++) {
Can you explain what this for loop is doing? I'm not really sure what it's doing from first glance.

2024-01-26 04:39 UTC, george-icarcover commented on src/app/(main)/car-covers/components/ProductContent.tsx
> +    let string = productAmount.toString();
Was unable to ultimately do this because productAmount is a number

2024-01-26 04:42 UTC, george-icarcover commented on src/app/(main)/car-covers/components/ProductContent.tsx
> +    for (let i = 5; i < string.length; i++) {
just starting at the 6th index in the string

2024-01-26 23:39 UTC, devwilliamy commented on src/app/(main)/car-covers/components/ProductContent.tsx
> +    let string = productAmount.toString();
Ooo sorry forgot about declaring types in Typescript, makes sense.

2024-01-26 23:39 UTC, devwilliamy commented on src/app/(main)/car-covers/components/ProductContent.tsx
> +    for (let i = 5; i < string.length; i++) {
Why did you pick the 6th? Is it arbitrary or was there another reason for it?

2024-01-26 23:45 UTC, devwilliamy approved these changes
Tested with different covers and cars and submodels, seem to be different enough

I responded to one of the conversations.

2024-01-27 02:37 UTC, george-icarcover commented on src/app/(main)/car-covers/components/ProductContent.tsx
> +    for (let i = 5; i < string.length; i++) {
arbitrary

2024-01-31 01:25 UTC, merged